config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :categories, :products, :favorites, :seller
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'edit', to: 'users#edit'
    get 'profile', to: 'users#edit'
    # get 'address', to: 'address#index'
  end

  devise_scope :address do
    get 'address', to: 'addresses#edit'
  end
  
  resources :users , only: [:index, :show, :edit, :update] do
    resource :addresses
  end
  # authenticated :user do
  #   root to: 'home#index', as: :root_app
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :get_categories
  before_action :get_user_address

  def index
    @users = User.all
    @products = Product.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html {redirect_to current_user, notice: 'You successfully updated your profile.'}
      else 
        format.html { render :edit }
      end
    end
  end

  private 

  def user_params
    params.require(:user).permit(
      :username,
      :first_name,
      :last_name,
      :bio,
      :avatar,
      :phone_number
    )
  end

  def get_categories
    @categories = Category.all
  end


  def get_user_address
    if current_user
      @address = current_user.address
    end
  end

end

app/views/home/_category.html.haml
.category
    .category-container
        .categories
            .shop-by-category
                %span.material-symbols-sharp
                    menu
                SHOP BY CATEGORY
            .deals-today
                %span.material-symbols-sharp
                    electric_bolt
                Deals Today
            .special-prices
                %span.material-symbols-sharp
                    sell
                Special Prices
            .fresh
                Fresh
            .frozen
                Frozen
            .fruits
                Fruits
            .grains
                Grains
            .vegetables
                Vegetables
        .recently-viewed
            %span.material-symbols-sharp
                cached
            Recently Viewed

app/views/home/_footer.html.haml
.footer
  .details
    .customer-service
      .title
        CUSTOMER SERVICE
      .contents
        = link_to 'Help Centre'
        = link_to 'Payment Methods'
        = link_to 'Bukid Coins'
        = link_to 'Order Tracking'
        = link_to 'Free Shipping'
        = link_to 'Return & Refund'
        = link_to 'Report Seller'
        = link_to 'Contact Us'
    .about-bukid
      .title
        ABOUT BUKID
      .contents
        = link_to 'About Us'
        = link_to 'Bukid Blogs'
        = link_to 'Bukid Careers'
        = link_to 'Bukid Mall'
        = link_to 'Seller Centre'
        = link_to 'Flash Deals'
        = link_to 'Media Contact'
    .payment
      .title
        PAYMENT
      .contents
        = link_to 'Cash on Delivery'
    .follow-us
      .title
        FOLLOW US
      .contents
        .facebook
          %i.fa-brands.fa-facebook
          = link_to 'Facebook'
        .instagram
          %i.fa-brands.fa-square-instagram
          = link_to 'Instagram'
        .twitter
          %i.fa-brands.fa-twitter
          = link_to 'Twitter'
        .linkedin
          %i.fa-brands.fa-linkedin
          = link_to 'LinkedIn'
    .bukid-app-download
      .title
        BUKID APP DOWNLOAD
  .copyright
    ©️ 2022 BukidMarkets. All Rights Reserved.

app/views/home/_nav.html.haml
.nav
  .header
    %a{:href => "/"}
      %img.image{:src => '/logo.png'}
      - if (request.path == '/sign_in' || request.path == '/users/sign_in')
        %span.login
          Log In
      - elsif (request.path == '/profile')
        %span.profile
          Profile
      - elsif (request.path == '/sign_up' || request.path == '/users')
        %span.profile
          Register
      - elsif (request.path == '/favorites')
        %span.profile
          Favorites
      - elsif (request.path == '/seller')
        %span.profile
          Seller Centre
      - elsif (request.path == '/products/new')
        %span.profile
          Add Product
      - elsif (request.path == '/products')
        %span.profile
          Products
      - elsif (request.path == '/address')
        %span.profile
          Address
    - if (request.path == '/')
      .search
        %select#drop-down{:name => "drop-down"}
          %option{:value => "0"} All Categories
          - if @categories
            - @categories.collect do |cat|
              %option{:value => cat.id }
                = cat.name
        %input.input{:placeholder => "I'm searching for.."}
        %span.material-symbols-sharp
          search
    .user
      - if current_user
        - if current_user.role == "buyer"
          - if !(request.path == '/seller')
            = link_to "Become a Seller", seller_index_path
        
      %a.favorite{:href => "favorites"}
        %span.material-symbols-sharp
          favorite
        .fav
          
      - if current_user
        - if current_user.avatar?
          %a.profile{:href => "/profile"}
            .user-image
              = image_tag(current_user.avatar.to_s)
        - elsif current_user.google_avatar?
          %a.profile{:href => "/profile"}  
            .user-image
              = image_tag(current_user.google_avatar.to_s)
        - else
          %a.profile{:href => "/profile"}
            %span.material-symbols-sharp
              person
      - else
        = link_to "Log In", sign_in_path

app/views/home/index.html.haml
= render 'category'

.home
  .cover-image
    = image_tag("cover1.jpg", class:"image")
    .cover
    .cover-details
      %span
        Wholesale Suppliers
      .mini-sub
        High quality at Low prices, Fresh from Farm
      = link_to "Shop Now", "#products"
  .sub-title
    %h1
      Recently Listed
  .products#products
    - @products.order(:id).each do |product|
      .card
        .image
          = image_tag(product.thumbnail.to_s)
        .details
          .title
            = product.title
            %span
              = User.find(product.user_id).username
          .location
            %span.material-symbols-sharp
              location_on
            #{User.find(product.user_id).address.city}, #{User.find(product.user_id).address.country}
          .inquire
            = link_to "Inquire Now", product
            = "₱#{product.price} / kilo"
        .favorite
          %i.fa-regular.fa-heart
        .share
          %i.fa-solid.fa-arrow-up-from-bracket