config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :categories, :products, :favorites, :seller
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'edit', to: 'users#edit'
    get 'profile', to: 'users#edit'
    # get 'address', to: 'address#index'
  end

  devise_scope :address do
    get 'address', to: 'addresses#edit'
  end
  
  resources :users , only: [:index, :show, :edit, :update] do
    resource :addresses
  end
  # authenticated :user do
  #   root to: 'home#index', as: :root_app
  # end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_rich_text :description
  has_one_attached :description
  
  validates :title, presence: true, length: { minimum: 2 }
  validates :description, presence: true, length: { in: 1..1000 }, allow_blank: true
  validates :price, presence: true
  validates :thumbnail, presence: true

  mount_uploader :thumbnail, ImgUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_categories

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to seller_index_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to seller_index_path, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to seller_index_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:category_id, :title, :description, :price, :thumbnail )
    end

    def set_categories
      @categories = Category.all.order(:name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.products-new
  = form_with(model: product, class:"form-product") do |form|
    - if product.errors.any?
      .error
        %h2
          = pluralize(product.errors.count, "error")
          prohibited this product from being saved:
        %ul
          - product.errors.each do |error|
            %li= error.full_message
    .product-name
      = form.label :Product_Name, class: "label-title" do
        Product Name
      = form.text_field :title, class:"input-title", autocomplete:"off"
      %h5 Do not exceed 10 characters when entering the product name.
    .price-category
      .product-category
        = form.label :category, class: "label-category" do
          Category
          %i.fa-solid.fa-circle-info
        = form.select :category_id, options_for_select(@categories.collect { |category|  [category.name, category.id] }) , class:"input-category"
        %h5 Choose between the categories.
      .product-price
        = form.label :Price, class: "label-price"
        .price-container
          = form.number_field :price, class:"input-price", autocomplete:"off"
          %h4 ₱
        %h5 Price per kilo in PHP.
    .product-description
      = form.label :Description, class: "label-description" do
        Description
        %i.fa-solid.fa-circle-info
      = form.rich_text_area :description, class:"input-description", autocomplete:"off"
    .product-thumbnail
      = form.label :thumbnail, class: "label-thumbnail"
      = form.file_field :thumbnail, direct_upload: true, class:"input-thumbnail"
    .add-back
      = form.button "Add Product", class: "product-submit", data: {turbo: false, disable_with: "<i class='fa-solid fa-spinner fast-spin'></i>"} do
        - if request.path == "/products/new"
          Add Product
        - else
          Update
      = link_to "Back", seller_index_path

app/views/products/_product.html.haml
%div{id: "#{dom_id product}"}
  %p
    %strong Title:
    = product.title
  %p
    %strong Price:
    = product.price
    Per Kilo
  %p
    %strong Category:
    = product.category.name
  %p
    %strong Description:
    = product.description
  %p
    %strong Phone Number:
    = User.find(product.user_id).address.phone_number
  %p
    %strong Seller:
    = User.find(product.user_id).username
  %p
    %strong Location:
    = User.find(product.user_id).address.city
    ,
    \#{User.find(product.user_id).address.country}

app/views/products/edit.html.haml
= render "form", product: @product

app/views/products/index.html.haml
.profile-display
  - if notice != nil
    %p.notice= notice
  .profile
    .profile-nav
      = link_to "Profile", profile_path
      = link_to "Address", address_path
      = link_to "Products", products_path
    .profile-edit
      - @products.each do |product|
        - if product.user_id == current_user.id
          = render product
          = link_to "Show", product
      = link_to "New", new_product_path

app/views/products/new.html.haml
= render "form", product: @product

app/views/products/show.html.haml
.display-inquire
  .inquire
    .thumbnail
      = image_tag(@product.thumbnail.to_s)
    .header-inquire
      .title
        = @product.title
      .price
        ₱#{@product.price} / Kilo
    .body-inquire
      .description
        Description:
        = @product.description
      .chat
        .seller
          - if User.find(@product.user_id).avatar?
            = image_tag(User.find(@product.user_id).avatar.to_s)
          - else
            = image_tag(User.find(@product.user_id).google_avatar.to_s)
          @#{User.find(@product.user_id).username}
        %div
          %i.fa-solid.fa-phone
          = User.find(@product.user_id).address.phone_number
        %div
          %a{:href => "mailto:#{User.find(@product.user_id).email}"}
            %i.fa-solid.fa-envelope
            = User.find(@product.user_id).email
        %div
          %i.fa-solid.fa-location-dot
          #{User.find(@product.user_id).address.city}, #{User.find(@product.user_id).address.country}
        %button
          Message




    